; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_speed = 115200
build_flags = 
	-std=gnu++17
	-DCORE_DEBUG_LEVEL=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-O3
board_build.partitions = huge_app.csv
lib_ignore = 
	AsyncTCP_RP2040W
	ESPAsyncTCP
lib_deps = 
	olikraus/U8g2 @ ^2.35.19
	bblanchon/ArduinoJson @ ^7.2.1
	adafruit/Adafruit BME280 Library@^2.3.0
	adafruit/Adafruit MPU6050@^2.2.6
	me-no-dev/ESPAsyncWebServer@^3.6.0

[env:native]
platform = native
test_framework = unity
build_flags = -std=c++17 -DNATIVE_BUILD -DUNITY_INCLUDE_DOUBLE
lib_extra_dirs = lib
test_filter = test_native
build_src_filter = -<*>
lib_deps = 
	adafruit/Adafruit BME280 Library@^2.3.0
	me-no-dev/ESPAsyncWebServer@^3.6.0
